apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ssh-known-hosts-configmap.yaml
  - haproxy-ssh-configmap.yaml

configMapGenerator:
  - name: api-config
    envs:
      - api.env
      - shared.env
  - name: ptools-config
    envs:
      - ptools.env
      - shared.env
