apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    10.3.45.81 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBK5CuSPTQxdpFbrO9thkYSaz06QmiJ+FD3bG8r6Biwr2VlruF995tPMTarvVJAtD4upyYo32Q88yVtpw2uEMbic= 
    10.3.45.81 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMHdtVQ9MOYm3zFr5OZgRZf+xrskp4gEbnDGnMCfSK6V 
    10.3.45.81 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFficoJQ6BzAc2AHplH15+noQMjvlSvP5TDmy4bCPGtIa1kne2nCIR0gbdbwnHbh9iUAOFP4Z/cyOrRn9b79PugLh88/Watq0Uf4ABjGRnEg+HuJ8QlkkhncWYNfdiDDPfE4V5YCauy7SsqnD9cojjfN9xZ/PwvvJndX0vSa5XNkAGuQgC0mmBJF9nqC0yjyOg/cHt/b5Bj9N6XPczzRWNRgGe1qSEd7oCbaJlgpcx4nEirRv5NyG8URHK6n2I2Rhk5O3h7UyJFNOwu8GJXDzf8jbP08Kz0JJuAmubXms0eGuj5VYtCU9CM/HW+o74OwII9vEUYzVic6377LgO4oub 

