apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKD5SwWcioWAlgGYEF6Oce+JyIvlzvlJ+wne1yWdnw/iwlKSA61tJBHDBShkid3N80n40ICJtAQ2cxWC3EQUHRY=
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHbrzy3hYF3goO5augjME06pM/4nMZwgL1Y31u1RhOw2
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCRA9m4sFehHmC8oAR5TVpMYcTu1cnQj7aC97JoiUKWZFSafXvo/GcuTdeTSxM60f0jrtIKCi5WtrF2p3kNzYUaHVPpdqJeg4RL+dvSV9mMotgBhaqIQVkc5Ze7B59+R7vYn4Aq84W1gjgJhU8fRSPXxLJhmWhCfgqLaHr6MnYIoHAG+i7FKGrkeyUxIe/VWaXxdTVf5+MhSh2t2ez2bx1hL5O6Rsf7zhXZ8FnFE0Q4t9Y71nquUoL0hNC4lzGgxj2sdGOQOBj2jLKApZDaSFkRYjr20F1ORsDC9nLjbzfert0bXlPHjl7wZAKagUv06DCMnLvkvHHyLrZ5moqkqHKf
