apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFio5ldSPHbAgGfpqsTtDlIa+btWS46VNR/QHN9sk9jg9uR3Z3+oT8x0Fq5EHJ0L4z0c/ccH8dhggZ0A/CUQiBY= 
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFNL9MOz1u6VJG169zkK+NnUhlcLaJpxG7LuHGoX02jT 
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCl7UFlI/zkKvMZ9TyWlptU3KbEYysoUQ8MYwSJWBMDj0/uAX2mrOnUz50SOHGd6ffCwLgCROAiUJv15xytpl1pgjoCxWkTt6qvrneNs2ZK4FxMOWZIFYcLD3c5603G9QgdUSLeuhvUr0LoLQ0NjzWD3CUJcO13rXF5ppRBwryszsBjrKYhTdYKt6qz8f2skjfEE6iOTF/Vu+zIzOuZmz2vjtaDr5yAmsWCpYWKWwpVgd/wq9jCoE4SJKpz6lCgWdMJOYtMWjVHMQyh27ivNabNHanVoYrOowZXCbYk9aLoIQ53rNYTLWXrmoYm6MlYVvnWcIFp32hTFmvL0Q2dTYvj 
