apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKHLm4mlnmnFK4n1R4JE4dFlCUK6PJt495W2s3Is1DyFJA2fF4YUYHIuIuQ4GFrqgq0xqQHMfmswnEry7BuFZrA= 
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCaYA5whyI95u8ZwQLckyf2+AcyQZfnTytbDGRuGw57 
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzXKZBLW3ziYtyYvloHtvyhYhNnTRcBcVmtSteYwAj+hExgXEVQG1IunNCZnrWySn+X25qgHk5CvE+9+6AuvkOgROypiX8nBwwnrX+didy2SntYulUhb7rJikx2Ip3Je24THye6HU5sCWrCsvyfVOzwyotoKW1Ne3Seflgps24jjfZvXmmbF1njd1Ttaasvx4n75Xcz6fABpcMGht+Kbezjb6m3OpHbkUAkKR9c624MfmgG7dsgTImXHHj9g698gMlqnj0pTw1mZ8rIpoVpmClAmEGPfzc1Y/iZu3ushbL1Z53F10tM0UHci2ltm/rAS8F4Pznocy+1SAVIR9cIRgL 
