apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    10.3.35.225 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMJyE6aCeFlEZoCs3iPsMXMSJ8RaRtvGXTbKDsjsnlLo2gfW7HFux3dxxNmk8NIOhjSSSgfwp1/S1MAOMN4J5s0= 
    10.3.35.225 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAFepdqRWy+fxF5UKonagX9hYVK8mX+N8Zk+Fo4sIvIg 
    10.3.35.225 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTn8wAT3rIjWcu5A/wt9+Dju0tmL91H6rahD3WGmiA7WJ/wBS5uBRZg1/U+Dbv8+fm/8T69v+pMXj+TxU4q7r1hL2ggkSKK5R6q1xyZjxBGCvP4xR4QtvO8R+X7+fp9/GB6gnw8QnWfIcW7dW2ujtsB833z3Fdt5bXb86gvQEyQi/eEpcSt1dAyRH4yfdCeT6wKLf30MdcxitIg3J7HCTiB5V0oKTsrKIWvS95GPrimEAkW1zMmpCtYZJDmcbbiiUrXTdKWOnaF+LCBqpu61exAWEH7LONeuB2ZN65GVOw3PdPYRjtr67qWuLXPfCItVhOvJnsB50ZiMHJ05jRUdH7
