apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBckz/mqFZaZr3a37JccEPg4Zgfijh5xuQhtObb+j6luuVYI8JVi/sxSJAIPR+xfnNDBnkih8mWhAuWUGEsMnKU= 
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK4A3gdDUasbvy4fDpzgh8eMnTUnfV9/agPnxDUUQNxv 
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2QvOmas1DMEduVjlcu96zEcLg/bp9+wBttJ19ba86K2V9Mtnr4Hb2JBUJ6hMDyCPBSXbOfUlku+fgDydZAX8facO3WmxvGYbRMSTP1E8wHDG5dbZjiFks0EGAwuXaGth/khp2xHi5RS7aD3qq4bS9wFB+xLtaD5El0imIiudlocbIW/vo4WXYzihHEqtehGB7O0sn6b1haY0adgAmwsep/hznZgL8/nvoOAryaDzk7Vjz88kGjOrxQJAIeWGPRROaf7yzZSNICSFlGO1JptCn908IteihAltCeVkweWnQZ12Iwwcs+Rpg4zLzNCdQscPxExuYNH9ZqWa5NjFHaaaT 
