apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCf0/zq3raGEAmNjEngzH2bNhBCT/znMetHxF/gUvAQ0yMZFZlRS6Ihk+DA3akNMfh2MuziiR0BP+sGiHrf7g+M=
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPc/70AJUY619dBPD4+L1253IxvfEZtcu/Tf+3kA5H5p
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnIMd8A9QXcrGpgpxBoVzZ4T7A8E7x28JZVB+3GEaT5ewWN1FpZgnZNtSsk5y0sPPTeQXRbphS6QckORw9Njl4W9Ew1LdJFbiYnRJcXAK+C3eDQ8G9+LbbxCB+hc+0OHmHkvuU9WeEEpTRuFUtDpsWV6CDEOTxkUV/d/c7H6iVotwU+4T+YeLdxhL7fNX0mUmZoLpKBtb20ioA5s8Qj/L4bkKqvxvocntDOReHu4l2X+PAwwRVczk1bNCqZ2IheMK/2Wd6hX/pnAqkmyEsqh5SiNU9rzfQe3rUW+LNZvlPWeMKFqi6pFcEVJwUuJ+uKfaUZ6dqYTgdCkIF5CYFVW7T
