apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG4lEpxKvSQHx37XZXDTskUPbg9Iz3qXyFlStoom+Xie3VqyOwfIfonwKBCrNn5KQRQz0yMy+qkhphUV0b66Rvo= 
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG25kaumun9MdKsGlfsTBNMZIH8WvxT1P9vIJ/IIPdfr 
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwOvRXGYMTTRF9+fiaxeYbM97bbXCmbyaav8jwh/O3P6iM3blWyT0DS02NDHzvgnVuVJFbhlj7mg3Ss04jXd/FMz9fqxpAWgdN/s9M9esO46o21uTO2MpGpKrx6kw3LI3xUaBkBDGWXjaRMPEzR3PLgGkhm5x9mkAJ00VyO9DzQA/rMEAkH3fhbFtyb0ZKKYKJD1/0tqYnLvopnjADXpq3R97ghDbzhSh9RYvNZBH6YfP5mEzmvwOTcFBthG9CkqQRncXiMMbXvn29yaLfwCpo10SSHgnwLbUmvSHD4F4XgR0n+dZyw4YS3JW3z0x4B7040UaeseVtGXB8G58ARYN/ 
