apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAzx7six6KpCXNP77vgm6ze66bw9z6bTTTFg8Hy3ePZGZNKMN3dKURtlP9NgOFP3LlDApG9Ui+c02B02b+GLNPg= 
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMenJ7raH0x97dgc8newYeWqZJ/UGKL2SnRVc6Mp3N1b 
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDlZ16Oa4eZjO2UJJvDOLTfD8gfVaHMLiywqYNbsdGvXDPXpLZ5i84PC2jy/Psa2fQZf9BIH+VKZ2b2iGzN46TSRxs/Z+1GPO8+4VVBaXd/exh0Antl5Sq2pS3pdYGE4+JKTzWPzdtvUJFioHL4m1VlbfrEWX/atffYVrdXFmU8yjt94kgWTY6+d/CAcENLkRT712Q3qbupoaiemMEQWyan+ykPuZfu1tVW1mrs0AV0CLOortUvTjAMszIvxugd6VnBx1pJaoXGwIWBHO4zpVEhqhD++E+L6GOQXDcD2z1rf7cDSYRIwnxs8tl3igwAAqQsNS5DfEWETxIoOeZSnaTn 
