apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBADhzwJWFrI8xL2D8Cmay+fOyqtYnmYe6Blsy4tPzIdKCV16z59CYBDFZjc3vgFYVXxC6tEnMPteNH7Cu3afKOs= 
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBl+whFGqMfySUb2ETS7g6Mwapl+HoiM6T9NdQ0axr6V 
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuzV6KfqRhHnen7/N9zSM3b2oU51r5D4uoHfJVWtRTBK5zWftGFoWBU/L0a0azOVc1YBQWBmifQCpCGxeZhIJYtNstXpr1yMCoO78y0Km3a1A9G0utlQ3sjUWFxeZkLHo9s5V9sFPbdHfMMOupP5Kf9yASDWgZpZYa1v5L8v+sIunOGxInwpRnQB6YIqEFljWLG10gl3CCG0xkAQ1DFQz4DtncZ+orlh3NrIvmsb718vHg5P5t9kzi2Lm0LkHY4yrBQHv0v2ExZLjNZoSswqitIiSPFKpdS4REFv/eTliIIAqFS4bIt/WWKWG4Qyq1NX2SuoWOzYneAg095s3h1nBd 
