apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
data:
  known_hosts: |
    login-node.pcs.internal ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBB6mKbmiVBq6uLS1P+eCXKtHoJ3aS5ijFyamiKY8OTLv0DzGBwVMMtnMboZIA15X4CcZH42WDsg/dFAZsk2Oi+U= 
    login-node.pcs.internal ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHYq9EdO4buGf9XNR7we42jtvzpFx1rkK9su3XyHzPCv 
    login-node.pcs.internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOthFF3Pzugt5CcWTjdQZeJznRycXrA3kF7WMVghmqRr2SaBcmsaJoP5xS/u1Vu+w4OTib1ifRTwhYuK5DvTfs+E/pbN5Io+BWVpxK4QRtm6Ay97c1c0QdGN1bMDgSHDcFUR5smcN3A2MK8mj4A87ghwJjE0nZgrPRHhmU5Dfm93yFzafTgXQHOwvRPUmEh8Y9pYRz+mG+Cidt79yFhGiXBIeMKiW+nAevC5JfjH75OU4aOzqdOtKy78in5Uhk+PlYFr94Z+vCYIfNp7grHqqADByEhDYxaO43wU5AwbXLGkRzZcmadRqWMkbMql4A5Dxh6nmbChEK40M72PJ460Qj 
