apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sms-api-rke

images:
  - name: ghcr.io/vivarium-collective/sms-api
    newTag: 0.3.3

resources:
  - alembic-job.yaml
  - secret-shared.yaml
  - secret-ghcr.yaml
  - ../../config/sms-api-rke-dev
